[Submission] Sarkar, Benetos, Sandler
mdx-workshop/mdx-submissions21 pull request #31
Opened 2021-10-28 15:56 UTC by saurjya

**AUTHOR**

Dear mdx workshop committee,

I request a review for the following MDX submission:

### **Title:** Monotimbral Ensemble Separation using Permutation Invariant Training

**Author(s):**  Saurjya Sarkar, Emmanouil Benetos, Mark Sandler

**Category *** : 

* [ ] `POSTERS` _(+Abstract: 250 Words+one page pdf)_
  > As a participant of the MDX challenge, please know that your poster would be automatically accepted after a minimal prescreening. Hence, don't forget to provide us with the link to your team in the AIcrowd website.
  > You are also welcome to submit us some unrelated abstract, in case your interest would be in presenting some method or idea you would just like to discuss with the participants passing by.  
  > => You *don't* need to include your poster in the PR. Just be ready to have it for D-day and show it to the audience through screen sharing.
* [x] `LONG TALK`
  > A long talk will last about 20-30min, including questions. This can be about some recent paper you published, or may also present some original research and investigations you did. If you pick this category, please provide us with an extended abstract of the talk, or directly with the slides if you have them available, even in an unfinished state, at your convenience. 
* [ ] `DISCUSSIONS`
  > This category is intended to stimulate fruitful discussions and collaborations. If you pick it, it means you are willing to chair some open discussion with the participants, mainly around one particular aspect of music demixing research. For that purpose, you should provide a minimal abstract as well as a list of a few questions you would like the participants to discuss about. Don't hesitate to propose ideas, We will possibly contact you in case we identify several similar topics that were proposed!

**Preferred Timezone***

* [x] A 11:00 PM (PDT) to 9:00 AM PDT
* [ ] B 11:00 AM (PDT) to 9:00 PM PDT

  > The preferred timezone will help us to organize the day schedule. You should select at least one, but can perfectly select both if you don't care. We will organize the programme so that to maximally fit your preferences.
---

**ORGANISATION COMMITTEE (do not fill out)**

* [x] Editor acknowledgment
* [x] Reviewer 1 
* [ ] Reviewer 2
* [x] Review 1 decision [accept]
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

2021-11-01 07:01 UTC, aliutkus commented
Hi, thanks a lot for the submission
the abstract being quite short, is there some place we could check a longer version corresponding to what you intend to present ?

2021-11-01 14:33 UTC, saurjya commented
Hi,

So the presentation will be 50% my work on Vocal Harmony Separation and 50% will be my ongoing work on string ensemble which hasn't been published/presented so far. For the Vocal Harmony Separation part, here is the [paper](https://www.isca-speech.org/archive/pdfs/interspeech_2021/sarkar21_interspeech.pdf) and you can find a short presentation about the same [here](https://youtu.be/e96l5T6bAzs). Regarding the latter half of the content, I can share my content in a couple of days once it's finalized.

Hope this helps.

2021-11-03 05:39 UTC, aliutkus reviewed
Very nice work on ensemble separation that should bring some fresh air

2021-11-03 05:39 UTC, aliutkus commented on paper.md
> +Majority of research in Music Source Separation is focussed around the "Music De-mixing" problem of separating vocals, drums and bass from mastered songs. We have seen that the quality of separation
* "The" or "A" majority
* "monotimral"

2021-11-04 21:58 UTC, faroit requested changes
Hi @saurjya this looks great. Maybe you could just add a couple of references to this abstract so that I becomes more "feature-complete"?

E.g add the references that you mentioned here https://github.com/mdx-workshop/mdx-submissions21/pull/31#issuecomment-956285942

2021-11-04 21:58 UTC, faroit commented on paper.md
> +We first present our work based on Vocal Harmony Separation, where we utilise a time-domain neural network architecture re-purposed from speech separation research and modify it to separate a capella
The first sentence is rather long and I think it would be good if the "vocal harmony separation" can be defined more clearly

2021-11-04 21:58 UTC, faroit commented on paper.md
> +We also present our ongoing work on separating other monotimbral ensembles like string sections. To study this problem, we introduce a novel multitrack dataset generated using the Spitfire BBC Sympho
I suggest to add a few references to this section

2021-11-05 06:32 UTC, aliutkus reviewed
Choosing "accept". Please don't forget to update paper asap

2021-11-05 10:21 UTC, aliutkus commented
To all participants:
please note that you should update your submission by November 6th 23:00 UTC

Thank you very much

2021-11-05 11:27 UTC, saurjya commented
Hi,

Thanks a lot for the comments. I've made the requested changes. Also, apologies for the referencing to your other closed pull request in a couple of my recent commits. It was by mistake.

Best regards,
Saurjya

2021-11-06 22:31 UTC, faroit approved these changes

2021-11-08 23:55 UTC, faroit commented
👏 The submission has been published on midspace (the ISMIR conference platform). The submissions will also be hosted on the workshop website tomorrow. 

The schedule can be seen there or [here](https://docs.google.com/spreadsheets/d/1PaksFcHWUfNPMg-XloA3CJtrvb9uMU0erCFVyvFi9B4/edit?usp=sharing). Please let us know if there is anything missing. Otherwise we see each other on Friday/Saturday!

2022-04-13 07:25 UTC, faroit commented
Hi @saurjya, sorry for the long waiting time but I wasn't able to continue working on the proceedings before. 

I managed to finally work on cutting the video recordings of the workshop and plan to upload the recordings to YouTube very soon. In order to allow me to do this, please acknowledge the following:  

> I hereby authorize the right and permission to copyright and/or publish, reproduce or otherwise use my name, voice, and audio-visual recordings. I acknowledge and understand these materials about or of me may be used for both commercial and/or non-commercial purposes.

> I understand that my image may be edited, copied, exhibited, published and/or distributed. There is no time limit on the validity of this release nor are there any geographic limitations on where these materials may be distributed.

> I authorize that the video will be made available under the [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) on the conference website.

and comment on this by replying with `acknowledge`.

2022-04-13 09:52 UTC, saurjya commented
acknowledge

2023-09-08 12:11 UTC, closed without merging